### ISSUE TITLE
Create a Twitter Bot

### ISSUE THREAD

**Issue by ghost** [KeepOurNetFree/keepournetfree.github.io#25]
Create a twitter bot that will retweet things with the hastag #KeepOurNetFree or #BroadbandPrivacy.  The https://twitter.com/KeepOurNetFree.

**Comment by jacobherrington** [comment]
If all you want it to do is retweet, check this out:
https://www.labnol.org/internet/retweet-favorite-twitter-bot/28967/

**Comment by ZaneH** [comment]
Nice find Jacob, that could be setup within a couple of minutes by whoever​ owns the Twitter account.

**Comment by aptlyundecided** [comment]
Twitter Bot V1.0.0 is running
