### ISSUE TITLE
Find a Better Way to Handle Sensitive Data

### ISSUE THREAD

**Issue by ghost** [KeepOurNetFree/keepournetfree.github.io#35]
Not everyone scrub needs access to logins/passwords for everything.  We should figure out a better permissions system then Discord channels.

**Comment by ZaneH** [comment]
I think it should be manually handled.

Possible solutions:

- If there are invite-only channels on Discord do that and pin the creds to the channel

- DM individually each person who needs access

I'm sure there are more, but those are just off the top of my head.

**Comment by ZaneH** [comment]
Looks like this has been sorted. Closing.
