### ISSUE TITLE
Make a Discord Bot

### ISSUE THREAD

**Issue by ghost** [KeepOurNetFree/keepournetfree.github.io#38]
Wire up a quick and dirty bot to welcome newcomers to the Discord server and direct them to how they can help.  The bot should also subwatch so that moderators on the sub in #pr can be informed about new posts to the sub.  It might be handy to have the bot gitwatch too.

**Comment by JSDempsey** [comment]
I've gotten the bot doing welcome messages, pushed to repo

**Comment by JSDempsey** [comment]
Finished Reddit post broadcasting implementation
