### ISSUE TITLE
Some Stupid Shit That Won't Ever Fucking Work Right.

### ISSUE THREAD

**Issue by ghost** [KeepOurNetFree/keepournetfree.github.io#4]
Find a way to send email from the mail.html page.

**Comment by jacobherrington** [comment]
Are you thinking this is as simple as a mailto: in the HTML?

**Comment by ghost** [comment]
Congress doesn't have public email addresses anymore, so this is looking like a dead end.

**Comment by jacobherrington** [comment]
I think the link to "find my congressperson" is enough for the moment.
