### ISSUE TITLE
Get Google to Find www.KeepOurNetFree.org

### ISSUE THREAD

**Issue by ghost** [KeepOurNetFree/keepournetfree.github.io#45]
Self explanatory.

**Comment by gslette** [comment]
https://www.google.com/webmasters/tools/submit-url

Looks like we need to add it here. I can submit it, but I'm not entirely sure if that will cause it to be under my personal google account/gmail.

**Comment by ZaneH** [comment]
First result when searching "Keep Our Net Free"

For Google, Bing, and DuckDuckGo. Didn't check any others because the rest are irrelevant.
