### ISSUE TITLE
Create a Page for the Site on Defensive Browsing

### ISSUE THREAD

**Issue by ghost** [KeepOurNetFree/keepournetfree.github.io#47]
This should be a page detailing how users can protect themselves online.
Stuff like how to use VPN, which ones are best, what tor is, etc...
Safe browsing habits.
etc.

**Comment by zuve** [comment]
https://docs.google.com/document/d/10FQx8oEY4bvq-XUEEoG3bng-y4Zl4fjtoKaf6GeJayU/edit
Doc about defensive browsing
