### ISSUE TITLE
Make a New Tweeter Bot

### ISSUE THREAD

**Issue by ghost** [KeepOurNetFree/keepournetfree.github.io#80]
https://twitter.com/NetFreedomBot

Ideally, this should be done in Python.  Get creative with this one, just keep it safe for work.

**Comment by aptlyundecided** [comment]
Someone else better take point on this.  I've got a big project I'm focusing my free time on right now.  Kind of in the 'last half of the marathon' stage on it.

sorry.

**Comment by ghost** [comment]
No worries, we understand.  I'll tackle this when I get the chance.

**Comment by ghost** [comment]
Twitter account was banned. *()
